src/pages/auth/Login.tsx
src/services/auth.ts
src/services/content.tsx
src/services/home.ts
src/utils/api.ts

Implement Token Management with Access and Refresh Tokens : https://tracker.tekdi.net/issues/230728
Implement Authorization Interceptor : https://tracker.tekdi.net/issues/230750

Task #230728 [FE] Implement Token Management with Access and Refresh Tokens &  Task #230750 [FE] Implement Authorization Interceptor

---

public/content-player/demoData.js
public/content-player/index.html
public/content-player/script.min.1.1.js
public/video/index.html
src/pages/videos/VideoReels.tsx
src/pages/videos/utils.tsx

https://github.com/user-attachments/assets/524b9fd2-26d1-4ce4-8be5-9124cd749cdf

Capture and Track YouTube Telemetry for Sunbird with Progress Updates

---

src/App.jsx
src/pages/Home.tsx
src/pages/auth/Login.tsx
src/pages/videos/VideoReels.tsx
src/services/auth/auth.ts
src/services/content.tsx
src/services/home.ts
src/utils/constants/url-constants.json

https://tracker.tekdi.net/issues/231212

Task #231212 : [FE] Integrate Token Validation API Across All Pages

---

package.json
src/main.jsx

https://tracker.tekdi.net/issues/231428

Task #231428 [FE] fix: Added Sentry in app

---

.gitignore
src/components/players/SunbirdPlayer.tsx
src/pages/videos/VideoReels.tsx
src/services/content.tsx

https://tracker.tekdi.net/issues/231225

Task #231225: [FE] Integrate DIKSHA and Sunbird Content List API with Adapter Payload

---

.github/workflows/gla-prod-pilot-deploy.yml
package.json
public/content-player/demoData.js
public/pdf/index copy.html
public/pdf/index.html
public/quml/demoData.js
public/video/index copy.html
public/video/index.html
src/components/common/layout/layout.tsx
src/components/players/SunbirdPlayer.tsx
src/pages/videos/VideoReels.tsx
src/services/auth/auth.ts
src/utils/constants/url-constants.json

* Implemented telemetry tracking for login and logout actions.
* Updated telemetry configurations to include user ID in the configuration for better tracking and alignment with project standards.
* Addressed the issue of lessonId being null during telemetry tracking, ensuring complete event payloads.

Add Login and Logout Telemetry; Fix Player Telemetry; Resolve Lesson ID Null Issue

---

.github/workflows/develop-gla-deploy.yml
package.json
public/content-player/demoData.js
public/pdf/index.html
public/quml/demoData.js
public/video/index.html
src/App.jsx
src/pages/Home.tsx
src/pages/auth/Login.tsx
src/pages/videos/VideoReels.tsx
src/services/auth/auth.ts
src/services/content.tsx
src/services/home.ts
src/utils/constants/url-constants.json

Add Login and Logout Telemetry; Fix Player Telemetry; Resolve Lesson, refresh token

Resolved conflicts UAT merge into prod

---

public/content-player/demoData.js
public/pdf/index.html
public/quml/demoData.js
public/video/index.html
src/pages/videos/VideoReels.tsx
src/pages/videos/index.tsx

* Updated the telemetry data to include grade, medium, board, subject, and program in both CData and tags for more detailed tracking.
* Ensured that the telemetry configuration now captures these additional fields for improved content tracking and analytics.
* This update allows for better data segmentation and insights based on the user's educational attributes.

Update Grade, Medium, Board, Subject, and Program in CData and Tags Telemetry

---

src/App.jsx
src/pages/videos/VideoReels.tsx
src/pages/videos/index.tsx
src/services/auth/auth.ts

Update username and school_udise in telemetry cdata and tags

---

.github/workflows/develop-gla-deploy.yml
src/pages/Home.tsx
src/pages/videos/VideoReels.tsx
src/services/auth/auth.ts
src/utils/constants/url-constants.json

Resove Conflict Merge Prod into Dev 

---

src/pages/videos/VideoReels.tsx

Update Telemetry cdata and tags Types: question_set and learning_content

---

src/pages/auth/Login.tsx
src/services/auth/auth.ts

* Enhanced login and logout telemetry to include cdata and tags fields.
* Added the following metadata for better tracking:
* grade
* medium
* board
* username
* school_udise
* program

Task #0000: [FE] Update telemetry for login and logout CDATA and tags: grade, medium, board, username, school UDISE, and program.

---

src/pages/videos/VideoReels.tsx
src/pages/videos/utils.tsx

Fix tracking progress issue

---

src/components/common/cards/ContentCard.tsx
src/components/common/input/CustomDropDown.tsx
src/pages/Home.tsx
src/pages/videos/SearchPage.tsx

Task #0000 : Home page search issue

Task #0000 : Home page search issue

---

src/components/players/SunbirdPlayer.tsx
src/pages/videos/VideoReels.tsx

fix:auto play issue

---

public/content-player/index.html
public/content-player/youtube.html
public/content/preview/youtube.html
public/quml/index.html
src/components/players/SunbirdPlayer.tsx
src/pages/videos/VideoReels.tsx
src/pages/videos/index.tsx

Task #0000 Fix youtube and video Auto play issue 

---

src/components/common/layout/layout.tsx
src/pages/Home.tsx
src/pages/auth/Login.tsx
src/pages/videos/SearchPage.tsx
src/pages/videos/WatchScreen.tsx
src/pages/videos/index.tsx
src/services/auth/auth.ts

Fix: remove all localStorage keys on logout, increase content limit to 500, correct Odia spelling, and resolve home page content list issu

---

src/pages/videos/VideoReels.tsx
src/services/telemetry.ts

Task #0000 : [FE] Add a progress bar for each subject and overall user progress

---

public/content-player/index.html
public/content/preview/youtube.html
src/pages/videos/VideoReels.tsx
src/services/content.tsx

* Implemented telemetry capture for Quml when a quiz is started.
* Ensures tracking of user interactions at the beginning of a quiz for better analytics.
* Validated changes with unit tests and logs to confirm telemetry events are being recorded correctly.
* No breaking changes introduced.

Task #0000 : Capture Quml Telemetry on Start - Take a Quiz

---

public/locales/en/translation.json
src/components/common/icons/Icon.tsx
src/components/common/layout/Footer.tsx
src/components/common/layout/Header.tsx
src/components/common/layout/layout.tsx
src/pages/leaderboard/LeaderBoardScreen.tsx
src/routes/auth.tsx
src/services/home.ts
src/utils/constants/url-constants.json
src/utils/theme.tsx

https://tracker.tekdi.net/issues/233022

Task #233022 fix: [FE] Implement Leaderboard Screen with Filters and History Collapse

---

src/components/common/cards/ContentCard.tsx

https://tracker.tekdi.net/issues/233649?issue_count=161&issue_position=1&next_issue_id=233606

Task #233649 fix: Issue fix for take a quiz icon
